M48
; DRILL file {KiCad 7.0.7} date 2023 December 07, Thursday 16:32:06
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-12-07T16:32:06+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0276
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0827
%
G90
G05
T1
X4.8032Y-3.8661
X4.8032Y-4.2835
T2
X4.8032Y-3.5039
X4.8032Y-4.6457
X5.9449Y-3.5039
X5.9449Y-4.6457
T0
M30
